[theme]
# Verde esmeralda sobrio/oscuro (Color de acento para el botón y pestañas)
primaryColor = "#059669"

# Azul pizarra muy oscuro (Casi negro, muy elegante para el fondo)
backgroundColor = "#0f172a"

# Azul pizarra ligeramente más claro (Para el fondo de las cajas y formularios)
secondaryBackgroundColor = "#1e293b"

# Blanco/Grisáceo muy nítido para que el texto resalte con elegancia
textColor = "#f8fafc"

# Tipografía limpia
font = "sans serif"
